version: "3.8"

volumes:
  grafana_data:

services:
  grafana:
    image: grafana/grafana:8.2.7
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./configs/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
      - ./configs/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml:ro
      - ./configs/dashboards:/var/lib/grafana/dashboards:ro
  prometheus:
    image: prom/prometheus:v2.41.0
    depends_on:
      - nature_remo_exporter
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  nature_remo_exporter:
    build: .
    command:
      - -h
      - 0.0.0.0
    environment:
      - NATURE_ACCESS_TOKEN=${NATURE_ACCESS_TOKEN}
